#
# Executes commands at the start of an interactive session.
#

DOTDIR=${ZDOTDIR:-$HOME}

# Source Prezto.
if [[ -s "$DOTDIR/.zprezto/init.zsh" ]]; then
  source "$DOTDIR/.zprezto/init.zsh"
fi

# Customise to your needs...

# source dotfiles env
source "$DOTDIR/.my-dotfiles.env"

##
# print dropbox path
##
function dropbox()
{
  if command -v node >/dev/null 2>&1; then
    if [[ $OSTYPE = msys* ]]; then
      echo "Please update .zshrc with windows compatability, i think its in %APPDATA%\Dropbox\info.json"
    else
      echo $(node -e 'process.stdout.write(require(process.env.HOME + "/.dropbox/info.json").personal.path);');
    fi
  else
    echo "nodejs is required, improve with another way to read json or install node"
  fi
}

##
# helper to output installed atom modules
##
function dotfiles_apm-export()
{
  apm list -bi | grep -Eo '^[^@]+' > "$DOTFILES_INSTALLDIR/conf/apm_modules.txt"
}

##
# helper to install atom modules
##
function dotfiles_apm-install()
{
  apm install --packages-file "$DOTFILES_INSTALLDIR/conf/apm_modules.txt"
}

# mac only
if [[ $OSTYPE = darwin* ]]; then
  # mac dns flush helper
  alias dns='sudo dscacheutil -flushcache'
fi

# git config
export GIT_EDITOR='vim +startinsert'

# git is hard to type
alias gti=git
alias gt=git
alias got=git

# reduce git induced RSI
alias gc='git commit -v'
alias gs='git status'
alias gall='git add --all .'
alias gd='git diff'

# i like progress
alias rcp='rsync -aP'
alias rmv='rsync -aP --remove-source-files'

# reduce docker induced RSI
alias doco=docker-compose
alias dockerm=docker-machine
